Repository plain-bagel/AoC, pull requests merged in 2023-12, with the labels that each got.

#11 config: uncomment PyCharm specific gitignore entry
  .gitignore
Labels: config

#84 Day 9: Mirage Maintenance - @sunghwa.jun
  09/sunghwa.jun/day_09.in
  09/sunghwa.jun/day_09.livemd
Labels: aoc: solution

#77 Day 02: Cube Conundrum 문제 풀이 - @renardyreveur
  02/renardyreveur/Main.hs
  02/renardyreveur/StringParser.hs
Labels: aoc: solution

#73 Day 01: Trebuchet 문제 풀이 개선 - @renardyreveur
  01/renardyreveur/trebuchet.hs
Labels: aoc: solution

#78 Day 02: Applicative Parser Write up - @renardyreveur
  02/renardyreveur/applicative_parsers.pdf
Labels: aoc: write-ups

#95 Day 8: Haunted Wasteland 문제 풀이 - @renardyreveur
  08/renardyreveur/BaseParser.hs
  08/renardyreveur/Main.hs
Labels: aoc: solution

#98 Day 11: Cosmic Expansion 문제 풀이 - @renardyreveur
  11/renardyreveur/BaseParser.hs
  11/renardyreveur/Main.hs
Labels: aoc: solution

#7 Day 01: Trebuchet
  01/README.md
  01/etoile1224/01solution.py
  01/eunice-hong/README.md
  01/eunice-hong/solution.dart
  01/input.txt
  01/renardyreveur/README.md
  01/renardyreveur/rule_learning/README.md
  01/renardyreveur/rule_learning/checkpoints/trained_model_params.pkl
  01/renardyreveur/rule_learning/inference.py
  01/renardyreveur/rule_learning/res/incomp_elves.png
  01/renardyreveur/rule_learning/res/output_validation.png
  01/renardyreveur/rule_learning/res/training_log.png
  01/renardyreveur/rule_learning/trainer.py
  01/renardyreveur/rule_learning/training/data_generator.py
  01/renardyreveur/rule_learning/training/init_params.py
  01/renardyreveur/rule_learning/training/modelling/_activations.py
  01/renardyreveur/rule_learning/training/modelling/_base_layers.py
  01/renardyreveur/rule_learning/training/modelling/_normalization.py
  01/renardyreveur/rule_learning/training/modelling/calibration_model.py
  01/renardyreveur/rule_learning/training/modelling/loss_fn.py
  01/renardyreveur/rule_learning/training/optimizer.py
  01/renardyreveur/trebuchet.hs
  01/sunghwa.jun/day_01.livemd
  01/sunghwa.jun/day_01_1.in
Labels: aoc: problem

#13 Day02: Cube Conundrum
  02/README.md
  02/etoile1224/02solution.py
  02/eunice-hong/README.md
  02/eunice-hong/input.txt
  02/eunice-hong/solution.dart
  02/input.txt
  02/renardyreveur/Main.hs
  02/renardyreveur/StringParser.hs
  02/renardyreveur/applicative_parsers.pdf
  02/sunghwa.jun/day_02.in
  02/sunghwa.jun/day_02.livemd
Labels: aoc: problem

#16 Day 03: Gear Ratios
  03/README.md
  03/input.txt
  03/sunghwa.jun/day_03.in
  03/sunghwa.jun/day_03.livemd
Labels: aoc: problem

#22 Day 04: Scratchcards
  04/README.md
  04/input.txt
  04/sunghwa.jun/day_04.in
  04/sunghwa.jun/day_04.livemd
Labels: aoc: problem

#26 Day 05: If You Give A Seed A Fertilizer
  05/README.md
  05/input.txt
  05/sunghwa.jun/day_05.in
  05/sunghwa.jun/day_05.livemd
Labels: aoc: problem

#30 Day 06: Wait For It
  06/README.md
  06/eunice-hong/README.md
  06/eunice-hong/input.txt
  06/eunice-hong/solution.dart
  06/input.txt
  06/sunghwa.jun/day_06.livemd
Labels: aoc: problem

#54 Day 07: Camel Cards
  07/README.md
  07/input.txt
  07/sunghwa.jun/day_07.in
  07/sunghwa.jun/day_07.livemd
Labels: aoc: problem

#56 Day 08: Haunted Wasteland
  08/README.md
  08/eunice-hong/README.md
  08/eunice-hong/input.txt
  08/eunice-hong/solution.dart
  08/input.txt
  08/renardyreveur/BaseParser.hs
  08/renardyreveur/Main.hs
  08/sunghwa.jun/day_08.in
  08/sunghwa.jun/day_08.livemd
Labels: aoc: problem

#58 Day 09: Mirage Maintenance
  09/README.md
  09/eunice-hong/README.md
  09/eunice-hong/input.txt
  09/eunice-hong/solution.dart
  09/input.txt
  09/sunghwa.jun/day_09.in
  09/sunghwa.jun/day_09.livemd
Labels: aoc: problem

#60 Day 10: Pipe Maze
  10/README.md
  10/input.txt
Labels: aoc: problem

#65 Day 11: Cosmic Expansion
  11/README.md
  11/input.txt
  11/renardyreveur/BaseParser.hs
  11/renardyreveur/Main.hs
Labels: aoc: problem

#67 Day 12: Hot Springs
  12/README.md
  12/input.txt
Labels: aoc: problem

#71 Day 13: Point of Incidence
  13/README.md
  13/input.txt
Labels: aoc: problem

#74 Day 14: Parabolic Reflector Dish
  14/README.md
  14/input.txt
Labels: aoc: problem

#81 Day 16: The Floor Will Be Lava
  16/README.md
  16/input.txt
Labels: aoc: problem

#82 Day 17: Clumsy Crucible
  17/README.md
  17/input.txt
Labels: aoc: problem

#86 Day 18: Lavaduct Lagoon
  18/README.md
  18/input.txt
Labels: aoc: problem

#87 Day 19: Aplenty
  19/README.md
  19/input.txt
Labels: aoc: problem

#89 Day 20: Pulse Propagation
  20/README.md
  20/input.txt
Labels: aoc: problem

#90 Day 21: Step Counter
  21/README.md
  21/input.txt
Labels: aoc: problem

#91 Day 22: Sand Slabs
  22/README.md
  22/input.txt
Labels: aoc: problem

#92 Day 23: A Long Walk
  23/README.md
  23/input.txt
Labels: aoc: problem

#93 Day 24: Never Tell Me The Odds
  24/README.md
  24/input.txt
Labels: aoc: problem

#94 Day 25: Snowverload
  25/README.md
  25/input.txt
Labels: aoc: problem

#76 Day 15: Lens Library
  15/README.md
  15/input.txt
Labels: aoc: problem

#96 Day 9: Mirage Maintenance 문제 풀이 - @renardyreveur
  09/renardyreveur/BaseParser.hs
  09/renardyreveur/Main.hs
Labels: aoc: solution

#85 Day 6: Wait For It 문제 풀이 - @renardyreveur
  06/renardyreveur/BaseParser.hs
  06/renardyreveur/Main.hs
Labels: aoc: solution
